### ISSUE TITLE
Bug: Endless portal list

### ISSUE THREAD

**Issue by ljcooke** [Rotonde/beaker#46]
If you leave the site open for a while, the list of portals grows endlessly as duplicates are added.

This is especially noticeable if you make the list scrollable, e.g. by adding the following to custom.css:

```css
body #portal {
  position: absolute;
}
```
